language: java
sudo: false
addons:
  apt:
    packages:
    - parallel
install:
  - wget 'https://github.com/papyri/jing-trang/releases/download/xsd_bce_leap_years-1.0/jing.jar'
  - mkdir -p epidoc/8.13 epidoc/8.16 epidoc/8.23
  - wget -O epidoc/8.13/tei-epidoc.rng 'http://www.stoa.org/epidoc/schema/8.13/tei-epidoc.rng'
  - wget -O epidoc/8.16/tei-epidoc.rng 'http://www.stoa.org/epidoc/schema/8.16/tei-epidoc.rng'
  - wget -O epidoc/8.23/tei-epidoc.rng 'http://www.stoa.org/epidoc/schema/8.23/tei-epidoc.rng'
  - wget 'http://www.w3.org/TR/REC-rdf-syntax/rdfxml.rng'
script:
  - java -jar jing.jar rdfxml.rng RDF/collection.rdf
  - find HGV_trans_EpiDoc -name "*.xml" | parallel --gnu -X -j8 -u "java -jar jing.jar epidoc/8.13/tei-epidoc.rng {}"
  - find HGV_meta_EpiDoc -name "*.xml" | parallel --gnu -X -j8 -u "java -jar jing.jar epidoc/8.13/tei-epidoc.rng {}"
  - find DDB_EpiDoc_XML -name "*.xml" | parallel --gnu -X -j8 -u "java -jar jing.jar epidoc/8.16/tei-epidoc.rng {}"
  - find DCLP -name "*.xml" | parallel --gnu -X -j8 -u "java -jar jing.jar epidoc/8.23/tei-epidoc.rng {}"
